export const ACTIVE_BUTTON = 'ACTIVE_BUTTON'
export const FLIPPED_CARDS = 'FLIPPED_CARDS'
export const CLEAR_FLIPPED_CARDS = 'CLEAR__FLIPPED_CARDS'
export const MATCHED = 'MATCHED'
export const FLIPPED_OFF = 'FLIPPED_OFF'

